---

services:
  swoole-server:
    build:
      context: .
      dockerfile: swoole/Dockerfile
    restart: unless-stopped
    init: true
    # volumes:
    #   - ./swoole:/app:rw
    depends_on:
      - db
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  go-server:
    build:
      context: ./go
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  hyperf-server:
    build:
      context: .
      dockerfile: hyperf/Dockerfile
    restart: unless-stopped
    init: true
    # volumes:
    #   - ./hyperf:/app:rw
    depends_on:
      - db
    ports:
      - 8082:8082
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  db:
    image: postgres
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_WAL_BUFFERS: 16MB
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=200

volumes:
  dbdata:
    driver: local
