---

services:
  swoole-server:
    build:
      context: .
      dockerfile: swoole/Dockerfile
    restart: unless-stopped
    init: true
    # volumes:
    #   - ./swoole:/app:rw
    depends_on:
      - db
      - redis
    ports:
      - ${SWOOLE_PORT}:8080
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  go-server:
    build:
      context: ./go
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - ${GO_PORT}:8081
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  hyperf-server:
    build:
      context: .
      dockerfile: hyperf/Dockerfile
    restart: unless-stopped
    init: true
    # volumes:
    #   - ./hyperf:/app:rw
    depends_on:
      - db
      - redis
    ports:
      - ${HYPERF_PORT}:8082
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  laravel-server:
    build:
      context: .
      dockerfile: laravel/Dockerfile
    restart: unless-stopped
    # volumes:
    #   - ./laravel:/app:rw
    command: unitd --no-daemon --user laravel --group laravel --control unix:/tmp/control.unit.sock
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - ${LARAVEL_PORT}:8083
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  octane-server:
    build:
      context: .
      dockerfile: octane/Dockerfile
    restart: unless-stopped
    init: true
    command: ["--workers=4", "--task-workers=4", "--max-requests=10000"]
    # volumes:
    #   - ./octane:/app:rw
    depends_on:
      - db
      - redis
    ports:
      - ${OCTANE_PORT}:8084
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  node-server:
    build:
      context: .
      dockerfile: node/Dockerfile
    restart: unless-stopped
    environment:
      - WORKER_COUNT=4
    depends_on:
      - db
      - redis
    ports:
      - ${NODE_PORT}:8085
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

  db:
    image: postgres
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_WAL_BUFFERS: 16MB
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=200

  redis:
    image: redis:alpine
    restart: unless-stopped

  redis-manager:
    build:
      context: ./redis
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  dbdata:
    driver: local
